- name: Update and upgrade packages
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        cache_valid_time: 86400 # One day
        update_cache: yes
        upgrade: yes

