- name: Init Version
  hosts: localhost
  connection: local
  tasks:
    - name: Fetch latest commit hash from GitHub API
      command: curl -s "https://api.github.com/repos/chris-de-leon/infra-ubuntu/commits/master"
      register: git_response

    - name: Extract commit hash using jq
      shell: echo '{{ git_response.stdout }}' | jq -erc '.sha'
      register: commit_hash

    - name: Add commit hash to {{ ansible_env.HOME }}/.bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export INFRA_UBUNTU_REV="{{ commit_hash.stdout }}"'
        regexp: 'export INFRA_UBUNTU_REV=.*$'
        create: yes
        state: present
