- name: Init Git
  hosts: localhost
  connection: local
  vars:
    uname: "{{ lookup('env', 'GH_UNAME') }}"
    token: "{{ lookup('env', 'GH_TOKEN') }}"
    email: "{{ lookup('env', 'GH_EMAIL') }}"
    name: "{{ lookup('env', 'GH_NAME') }}"
  tasks:
    - name: Set Git user name
      git_config:
        name: user.name
        value: "{{ name }}"
        scope: global

    - name: Set Git user email
      git_config:
        name: user.email
        value: "{{ email }}"
        scope: global

    - name: Set Git editor to vim
      git_config:
        name: core.editor
        value: "vim"
        scope: global

    - name: Set Git credential helper to store
      git_config:
        name: credential.helper
        value: "store"
        scope: global

    - name: Set git init default branch
      git_config:
        name: "init.defaultBranch"
        value: "master"
        scope: global

    - name: Set git safe directory
      git_config:
        name: "safe.directory"
        value: "*"
        scope: global

    - name: Add Personal Access Token to {{ ansible_env.HOME }}/.git-credentials
      lineinfile:
        path: "{{ ansible_env.HOME }}/.git-credentials"
        line: "https://{{ uname }}:{{ token }}@github.com"
        create: yes
        state: present
        regexp: "^https://.*@github.com$"
