- name: Init Git credentials
  hosts: localhost
  tasks:
    - name: Add Personal Access Token to {{ ansible_env.HOME }}/.git-credentials
      lineinfile:
        path: "{{ ansible_env.HOME }}/.git-credentials"
        line: "https://{{ uname }}:{{ token }}@github.com"
        create: yes
        state: present
        regexp: '^https://.*@github.com$'

