- name: Init Git Configs
  hosts: localhost
  connection: local
  vars:
    email: "{{ lookup('env', 'GH_EMAIL') }}"
    name: "{{ lookup('env', 'GH_NAME') }}"
  tasks:
    - name: Set Git user name
      git_config:
        name: user.name
        value: "{{ name }}"
        scope: global

    - name: Set Git user email
      git_config:
        name: user.email
        value: "{{ email }}"
        scope: global

    - name: Set Git editor to vim
      git_config:
        name: core.editor
        value: "vim"
        scope: global

    - name: Set Git credential helper to store
      git_config:
        name: credential.helper
        value: "store"
        scope: global

    - name: Set git init default branch
      git_config:
        name: "init.defaultBranch"
        value: "master"
        scope: global

    - name: Set git safe directory
      git_config:
        name: "safe.directory"
        value: "*"
        scope: global
