- name: Undo Git Credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure {{ ansible_env.HOME }}/.git-credentials file is deleted
      file:
        path: "{{ ansible_env.HOME }}/.git-credentials"
        state: absent
