- name: Configure Docker Group
  hosts: localhost
  connection: local
  tasks:
    - name: Get USER
      command: echo "$USER"
      register: user

    - name: Add user to Docker group
      user:
        name: "{{ user.stdout }}"
        groups: docker
        append: yes
      become: yes

