- name: Init Version
  hosts: localhost
  connection: local
  tasks:
    - name: Fetch latest commit hash from GitHub API
      command: curl -s "https://api.github.com/repos/chris-de-leon/infra-ubuntu/commits/master"
      register: git_response

    - name: Extract commit hash using jq
      shell: echo '{{ git_response.stdout }}' | jq -erc '.sha'
      register: commit_hash

    - name: Install ubctl
      command: nix build "git+https://github.com/chris-de-leon/infra-ubuntu?rev={{ commit_hash.stdout }}"#ubctl --print-out-paths
      register: ubctl_dir

    - name: Add ubctl function to {{ ansible_env.HOME }}/.bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'ubctl() { {{ ubctl_dir.stdout }}/bin/ubctl "$@"; }'
        regexp: '^ubctl\(\) \{.*\}$'
        create: yes
        state: present

