# https://docs.docker.com/engine/install/debian/#uninstall-docker-engine
- name: Undo Docker
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Purge Docker Engine, CLI, containerd, and Docker Compose packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce-rootless-extras
        state: absent
        purge: yes
        force: yes

    - name: Remove Docker and containerd data
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /var/lib/containerd

    - name: Remove Docker source list
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove Docker keyring
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Update package cache
      apt:
        update_cache: yes
