- name: Undo Docker Group
  hosts: localhost
  connection: local
  tasks:
    - name: Get USER
      command: echo "$USER"
      register: user

    - name: Remove user from Docker group
      command: "deluser {{ user.stdout }} docker"
      become: yes
