# name: PR Checks

# on:
#   pull_request:
#     branches:
#       - master

# jobs:
#   verify-build:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout repository
#         uses: "actions/checkout@v4"

#       - name: Install Nix
#         uses: "cachix/install-nix-action@v17"

#       - name: Verify Build
#         run: nix develop .#dev --command bash -c 'make build'

#   verify-hash:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout repository
#         uses: "actions/checkout@v4"

#       - name: Install Nix
#         uses: "cachix/install-nix-action@v17"

#       - name: Verify Hash
#         run: nix develop .#dev --command bash -c 'make version'

#   verify-release:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout repository
#         uses: "actions/checkout@v4"

#       - name: Install Nix
#         uses: "cachix/install-nix-action@v17"

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Verify Release
#         run: nix develop .#dev --command bash -c 'DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" make release.local'
