name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Verify Build
        run: nix develop .#dev --command bash -c 'make build'

      - name: Verify Hash
        run: nix develop .#dev --command bash -c 'make version'

      - name: Log into Docker
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Verify Release
        run: nix develop .#dev --command bash -c 'DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" make release.local'
