name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # grant permissions to create releases

jobs:
  check-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Check Build
        run: nix develop .#dev --command bash -c 'make build'

  check-hash:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Check Hash
        run: nix develop .#dev --command bash -c 'make version'

  release:
    runs-on: ubuntu-22.04
    needs: [check-build, check-hash]
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4"

      - name: Install Nix
        uses: "cachix/install-nix-action@v17"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Release
        run: nix develop .#dev --command bash -c 'DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" make release.github.strict'
